name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Generate key
        run: php artisan key:generate

      - name: Install JS dependencies
        run: npm install
      - name: Compile frontend assets
        run: npm run build

      - name: Create Testing Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          AUTH0_DOMAIN: ${{secrets.PROD_AUTH0_DOMAIN}}
          AUTH0_CLIENT_ID: ${{secrets.PROD_AUTH0_CLIENT_ID}}
          AUTH0_CLIENT_SECRET: ${{secrets.PROD_AUTH0_CLIENT_SECRET}}
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
          XDEBUG_MODE: coverage
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          version: '10.1'
          php_version: '8.3'
          php_extensions: xdebug
          #args: --coverage-text
